### ISSUE TITLE
Mismatch output sequence alignment

### ISSUE THREAD

**Issue by chrzyki** [lexibank/phylogenetics-data-management-tutorial#5]
```python
alms = lingpy.Alignments(wl, transcription='form', ref="cogid", segments="segments")
alms.align(method='library')

print(lingpy.SCA(alms.msa['cogid'][5701]))
```

yields

```
-	-	-	e	j	-	u	-	-
-	-	-	a	ʒ	-	ɔː	-	-
-	-	-	a	z	-	ua	-	-
-	-	-	ə	j	-	ou	-	-
-	-	-	ɔ	j	-	ɔ	w	-
m	ɯ	³¹	-	ʑ	-	ua	-	⁵⁵
-	a	³³	-	ʑ	-	ua	-	¹¹
-	-	-	a	j	-	ɔː	-	-
-	-	-	e	j	-	o	-	-
-	-	-	ɔ	j	-	u	-	-
-	-	-	a	j	-	ɔː	-	-
-	-	-	a	j	-	ɔː	-	-
-	-	-	a	z	j	aː	-	-
-	-	-	a	ʤ	-	ua	-	-
-	-	-	e	j	-	o	-	-
-	-	-	a	j	-	ɔ	w	-
-	-	-	a	z	j	aː	-	-
-	-	-	a	j	-	ɔː	-	-
-	-	-	a	z	-	ua	-	-
-	-	-	a	j	-	ɔː	-	-
-	-	-	e	j	-	u	-	-
-	-	-	e	j	-	u	-	-
```

This is different from the sample tutorial output.

**Comment by tresoldi** [comment]
Hm, yes and not, I am a bit torn about this. This is the output one gets if the code for loading the lexibank dataset is run (the difference is due to the two Eastern Puroik languages collected by Sun and Li, with the additional prefix), the output currently in the tutorial is the one for the data in `cldf-khobwa`.

The issue is that the entire tutorial analysis, and including the Bayesian run reported in the chapter, was performed on the dataset we are distributing here, not on the lexibank one. This is why I originally wanted to put the lexibank stuff at the bottom, but it does make sense in the flow to have it where it is now.

I guess the best solution is to change variable name for the lexibank dataset from `wl` to something like `wl_lexibank`. What is your opinion?

**Comment by chrzyki** [comment]
Flow-wise it makes sense, I agree. The additional variables/different origins might be cause for additional confusion I'd say. At any rate, I just think that if output is provided, it should match what a person running the snippets is going to see.

**Comment by tresoldi** [comment]
Ok.
